### PR TITLE
Assign users to Public group on signup

### PR DESCRIPTION
**Pull request by lukehollis**
Now on signup, the form is processed and the new user is assigned to a "Public" group that needs to be created in the admin backend by a superuser. 

Should address https://github.com/artshumrc/giza/issues/94 -- I'll add the buttons for managing collections on the frontend in a separate issue after the Collections data model is adjusted.

### CODE REVIEW

**Comment by rsinghal** [comment]
Please rebase this branch against master to remove https://github.com/artshumrc/giza/pull/150/commits/6bcd113caeaee41021d376407b363a30f5a732ac from the list of changes

**Comment by lukehollis** [comment]
@rsinghal I rebased to master--let me know if this is as expected.

**Comment by ColeDCrawford** [comment]
@lukehollis Rashmi can take a look at this on Monday, but I'm still seeing the same modified files as #149 (`0004_lesson_summary.py`, `models.py`, `lesson-topic-blurb.html`). The changes in `0004_lesson_summary.py` and `models.py` are already in master, but the changes to `lesson-topic-blurb` look new. I thought the rebase was going to fix that but I guess not?

**Comment by lukehollis** [comment]
Hi @ColeDCrawford thanks for taking a look, and I followed instructions for what I thought was to `rebase master` -- I'll branch from `master` continually in future PRs, and for last weekend, I wanted to make sure that the migrations added were numbered correctly between PRs. Do you have a strategy for this that you prefer?

**Comment by rsinghal** [comment]
@lukehollis unfortunately, this didn't work as there are now more files changed than before.  You would need to rebase against artshumrc giza master, not your own.  See https://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html.  Alternatively, you can resubmit the PR with just the changes for this one.  Ultimately, I need to only see the files changed by the PR, not from other PRs, so I can review.

**Comment by lukehollis** [comment]
Hi @rsinghal let me know how this looks--now this PR should only contain the single commit.

**Comment by rsinghal** [comment]
Yes, this looks right! I'll get this up on dev for the team to test.

**Pull request merged**
